version: '3.8'
services:
    rl_dev_server:
        build:
            dockerfile: Dockerfile
            context: ./app
        ports:
          - 8666:8666
        volumes:
            - ./app:/app
        command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8666", "--no-browser", "--allow-root"]